# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^iwf/iwf_api/

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: https://github.com/hadialqattan/pycln
  rev: v2.5.0
  hooks:
  - id: pycln
    args: ["-a"]

- repo: https://github.com/ambv/black
  rev: 24.10.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.8.1"
  hooks:
  - id: ruff

- repo: local
  hooks:

  - id: mypy
    name: Validate types with MyPy
    entry: poetry run mypy
    language: system
    types: [python]
    pass_filenames: false
    args:
    - "iwf"

  - id: no-nexus
    name: Remove nexus references
    entry: .githooks/no-nexus.sh
    language: script
    types: [file] # Example: run on all files, adjust as needed
